# Generated by Django 5.1.6 on 2025-03-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('CatergoryName', models.CharField(max_length=60)),
                ('CatergoryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CatergoryImage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('ChefName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ChefImage', models.ImageField(upload_to='images/')),
                ('ChefPosition', models.CharField(blank=True, max_length=100, null=True)),
                ('ChefDescription', models.TextField(blank=True, null=True)),
                ('ChefSkills', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('Answer', models.TextField(max_length=500)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('FooterName', models.CharField(max_length=40)),
                ('FooterID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FooterURL', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MenuName', models.CharField(max_length=40)),
                ('MenuID', models.BigAutoField(primary_key=True, serialize=False)),
                ('MenuURL', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('BlogTitle', models.CharField(max_length=100)),
                ('BlogID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BlogDescription', models.TextField()),
                ('BlogImage', models.ImageField(upload_to='images/')),
                ('BlogDate', models.DateTimeField(auto_now_add=True)),
                ('BlogAuthor', models.CharField(blank=True, max_length=50, null=True)),
                ('Tags', models.CharField(blank=True, max_length=100, null=True)),
                ('CatergoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.catergory')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('OpenHour', models.CharField(max_length=100)),
                ('CatergoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.catergory')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductName', models.CharField(max_length=100)),
                ('ProductID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProductPrice', models.FloatField()),
                ('ProductImage', models.ImageField(upload_to='images/')),
                ('ProductDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.catergory')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GalleryName', models.CharField(blank=True, max_length=100, null=True)),
                ('GalleryImage', models.ImageField(upload_to='images/')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.products')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlideName', models.CharField(blank=True, max_length=100, null=True)),
                ('SlideBGImage', models.ImageField(upload_to='images/')),
                ('SlideThumbnail', models.ImageField(upload_to='images/')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.products')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialMediaURL', models.CharField(blank=True, max_length=300, null=True)),
                ('CatergoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.catergory')),
                ('SocialMediaID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.chef')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.products')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('SubMenuName', models.CharField(max_length=40)),
                ('SubMenuID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SubMenuURL', models.CharField(max_length=300)),
                ('MenuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.menu')),
            ],
        ),
    ]
