# Generated by Django 5.1.6 on 2025-03-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='SlideBGImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
