# Generated by Django 5.1.6 on 2025-03-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0002_alter_slide_slidebgimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ProductText',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
