# Generated by Django 5.1.6 on 2025-04-04 20:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0002_remove_chef_chefskills_chefskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutTitle', models.CharField(max_length=100)),
                ('AboutDescription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('AboutLeftBG', models.ImageField(upload_to='images/')),
                ('AboutRightBG', models.ImageField(upload_to='images/')),
                ('AboutLeftThumbnail', models.ImageField(upload_to='images/')),
                ('AboutRightThumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
