# Generated by Django 5.1.6 on 2025-04-04 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('TemplateID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TemplateName', models.CharField(max_length=100)),
                ('TemplateURL', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='footer',
            name='FooterURL',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='MenuURL',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='SubMenuURL',
        ),
        migrations.AddField(
            model_name='footer',
            name='TemplateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.template'),
        ),
        migrations.AddField(
            model_name='menu',
            name='TemplateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.template'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='TemplateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.template'),
        ),
    ]
