# Generated by Django 5.1.6 on 2025-03-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0003_products_producttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductDescription',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
