# Generated by Django 5.1.6 on 2025-04-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0004_alter_products_productdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='BlogImage',
            new_name='BlogThumbnail',
        ),
        migrations.AlterField(
            model_name='blog',
            name='BlogDescription',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
