# Generated by Django 5.1.6 on 2025-04-12 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0004_template_remove_footer_footerurl_remove_menu_menuurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='OfferImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
