# Generated by Django 5.1.6 on 2025-04-04 05:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0005_rename_blogimage_blog_blogthumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
