# Generated by Django 5.1.6 on 2025-04-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0005_specialoffer_offerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTAImage', models.ImageField(upload_to='images/')),
                ('CTABg', models.ImageField(upload_to='images/')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.products')),
            ],
        ),
    ]
