# Generated by Django 5.1.6 on 2025-04-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Restaurant', '0006_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.products')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_Restaurant.products')),
            ],
        ),
    ]
